[project]
name = "inspire-jobs-backend"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic-settings",
    "sqlalchemy",
    "psycopg[binary]",
    "pgvector",
    "requests",
    "alembic",
    "python-dotenv",
    "groq",
]

[tool.setuptools.packages.find]
include = ["app*"]
